#
# cxproc configuration
# 

# sudo a2enmod cgi actions proxy proxy_http alias
# sudo a2ensite cxproc-template.conf

Define CXP_PORT 8189

#Listen ${CXP_PORT}

<virtualhost *:${CXP_PORT}>
    #ServerName tupile.fritz.box
    #ServerAlias www.my-domain.tld

    #ProxyRequests Off
    #ProxyPass "/cxproc/test" "http://127.0.0.1:8888/"
    #ProxyPassReverse "/cxproc/test" "http://127.0.0.1:8888/"

    #Define CXP_PREFIX "C:/UserData/Develop/cxproc-build/x86-windows-debug"
    #Define WWW_PREFIX "${CXP_PREFIX}/www/html"
    #Define CGI_PREFIX "${CXP_PREFIX}/www/cgi-bin"
    #Define LOG_PREFIX "${CXP_PREFIX}/www/log"
    
    Define WWW_PREFIX "/var/www/html"
    Define CGI_PREFIX "/usr/lib/cgi-bin"
    Define LOG_PREFIX "/var/log/apache2"

    DocumentRoot "${WWW_PREFIX}"

    #
    # Content directory
    # - direct URL access via Apache
    # - Authorization
    # 
    <Directory "${WWW_PREFIX}">
	#htpasswd -c C:\User\passwords developer
	#AuthType Basic
	#AuthName "By Invitation Only"
	#AuthUserFile "C:/User/Starter/Settings/passwords"
	#Require valid-user 
        #Dav On
	#Options Indexes FollowSymlinks
	#DirectoryIndex index.cxp index.html
	Options All
	#AllowOverride All
	#AllowOverride None
	#Require local
	AddDefaultCharset off
    </Directory>

    <Location /server-status>
	SetHandler server-status
	Require local
    </Location>

    ErrorLog "${LOG_PREFIX}/cxproc-${CXP_PORT}-error.log"
    LogLevel warn
    CustomLog "${LOG_PREFIX}/cxproc-${CXP_PORT}-access.log" combined

</virtualhost>
