#
# cxproc configuration
# 

# sudo a2enmod cgi actions
# sudo a2ensite cxproc-template.conf

Define CXP_PORT 8189

Listen ${CXP_PORT}

<virtualhost *:${CXP_PORT}>

    Define CXP_PREFIX "/home/developer/cxproc-build/x86_64-gnu-linux"
    Define WWW_PREFIX "${CXP_PREFIX}/www/html"
    Define CGI_PREFIX "${CXP_PREFIX}/www/cgi-bin"
    Define LOG_PREFIX "${CXP_PREFIX}/www/log"
    
    #Define WWW_PREFIX "/var/www/html"
    #Define CGI_PREFIX "/usr/lib/cgi-bin"
    #Define LOG_PREFIX "/var/log/apache2"

    DocumentRoot "${WWW_PREFIX}/test/audio/"

    SetEnv CXP_LOG     3
    SetEnv CXP_READONLY "yes"
    SetEnv CXP_LOGFILE "${LOG_PREFIX}/cxproc-${CXP_PORT}.log"
    #
    SetEnv CXP_PATH  "${WWW_PREFIX}/audioserver/"

    #
    # Content directory
    # - direct URL access via Apache
    # - Authorization
    # 
    <Directory "/">
	DirectoryIndex index.html
	Options All
	AllowOverride All
	Require all granted
	AddDefaultCharset off
    </Directory>

    <Directory "${WWW_PREFIX}">
	DirectoryIndex index.html
	Options All
	AllowOverride All
	Require all granted
	AddDefaultCharset off
    </Directory>

    ScriptAlias /cxproc/exe	"${CGI_PREFIX}/cxproc-cgi"
    Action cxp-process "/cxproc/exe"
    AddHandler cxp-process .cxp

    #
    # Cxproc runtime and thirdparty Directory
    #
    <Directory "${CGI_PREFIX}">
	Require all granted
	Allow from all
	AddDefaultCharset off
    </Directory>

    ErrorLog "${LOG_PREFIX}/cxproc-${CXP_PORT}-error.log"
    LogLevel warn
    CustomLog "${LOG_PREFIX}/cxproc-${CXP_PORT}-access.log" combined

</virtualhost>
