################################################################################
#
# either local libcmark or system libcmark
#

# cmark source dir, required for internal header files
FIND_PATH(LIBCMARK_SRC_DIR NAMES "cmark.c" HINTS ${HINT_DIR_PARENT} PATH_SUFFIXES "cmark/src" NO_DEFAULT_PATH)
FIND_PATH(LIBCMARK_BUILD_DIR NAMES "config.h" HINTS "${LIBCMARK_SRC_DIR}/../build/src" NO_DEFAULT_PATH)

FIND_PATH(LIBCMARK_INCLUDE_DIR NAMES "cmark.h" HINTS ${LIBCMARK_SRC_DIR} NO_DEFAULT_PATH)
FIND_PATH(LIBCMARK_INCLUDE_DIR NAMES "cmark.h")

FIND_LIBRARY(LIBCMARK_LIBRARY NAMES "cmark.a" "cmark" HINTS ${HINT_DIR_LIB})
FIND_LIBRARY(LIBCMARK_LIBRARY NAMES "cmark")

IF (LIBCMARK_INCLUDE_DIR)
  IF (LIBCMARK_LIBRARY)
    INCLUDE_DIRECTORIES(${LIBCMARK_BUILD_DIR} ${LIBCMARK_INCLUDE_DIR} ${LIBCMARK_SRC_DIR})
    MESSAGE(STATUS "Found libcmark: ${LIBCMARK_LIBRARY}")
  ELSE ()
    MESSAGE(STATUS "Not found: libcmark")
  ENDIF ()
ELSE ()
  MESSAGE(STATUS "Not found: headers of libcmark")
ENDIF (LIBCMARK_INCLUDE_DIR)

#MESSAGE(FATAL_ERROR " ${LIBCMARK_LIBRARY}: ${LIBCMARK_SRC_DIR} ${LIBCMARK_INCLUDE_DIR} ${LIBCMARK_BUILD_DIR}")
