################################################################################
#
# libbz2
#

IF (HINT_DIR_INCLUDE)
  find_path(BZIP2_INCLUDE_DIRS NAMES "bzlib.h" HINTS ${HINT_DIR_INCLUDE} NO_CMAKE_FIND_ROOT_PATH) 
  find_library(BZIP2_LIBRARY_RELEASE NAMES bz2 bzip2 libbz2 libbzip2 HINTS ${HINT_DIR_LIB} NO_CMAKE_FIND_ROOT_PATH)
  find_library(BZIP2_LIBRARY_DEBUG NAMES bz2d bzip2d libbz2d libbzip2d HINTS ${HINT_DIR_LIBD} NO_CMAKE_FIND_ROOT_PATH)
ENDIF ()

IF (BZIP2_INCLUDE_DIRS AND BZIP2_LIBRARY_DEBUG)
  SET(BZIP2_LIBRARIES ${BZIP2_LIBRARY_DEBUG})
  MESSAGE(STATUS "Found debug libbz2: ${BZIP2_LIBRARIES}")
ELSEIF (BZIP2_INCLUDE_DIRS AND BZIP2_LIBRARY_RELEASE)
  SET(BZIP2_LIBRARIES ${BZIP2_LIBRARY_RELEASE})
  MESSAGE(STATUS "Found libbz2: ${BZIP2_LIBRARIES}")
ELSE()
  FIND_PACKAGE( BZip2 )
ENDIF ()

IF (BZIP2_INCLUDE_DIRS AND BZIP2_LIBRARIES)
  INCLUDE_DIRECTORIES(${BZIP2_INCLUDE_DIR})
  add_compile_definitions(HAVE_BZIP2)
  IF (${BZIP2_LIBRARIES} MATCHES "static.*\\.lib$" OR ${BZIP2_LIBRARIES} MATCHES "\\.a$")
    add_compile_definitions(BZIP2_STATIC)
  ENDIF ()
ENDIF ()
