################################################################################
#
# libcurl
#

IF (HINT_DIR_INCLUDE)
  find_path(CURL_INCLUDE_DIR NAMES "curl.h" HINTS ${HINT_DIR_INCLUDE} PATH_SUFFIXES "curl" NO_DEFAULT_PATH) 
  find_library(CURL_LIBRARY_RELEASE "curl" "libcurl" HINTS ${HINT_DIR_LIB} NO_DEFAULT_PATH)
  find_library(CURL_LIBRARY_DEBUG "curl-d" HINTS ${HINT_DIR_LIBD} NO_DEFAULT_PATH)
ENDIF ()

IF (CURL_INCLUDE_DIR AND CURL_LIBRARY_DEBUG)
  SET(CURL_FOUND TRUE)
  SET(CURL_LIBRARIES ${CURL_LIBRARY_DEBUG})
  MESSAGE(STATUS "Found libcurl: ${CURL_LIBRARIES}")
ELSEIF (CURL_INCLUDE_DIR AND CURL_LIBRARY_RELEASE)
  SET(CURL_FOUND TRUE)
  SET(CURL_LIBRARIES ${CURL_LIBRARY_RELEASE})
  MESSAGE(STATUS "Found libcurl: ${CURL_LIBRARIES}")
ELSE()
  FIND_PACKAGE( CURL )
ENDIF ()

IF (CURL_INCLUDE_DIR AND CURL_LIBRARIES)
  INCLUDE_DIRECTORIES(${CURL_INCLUDE_DIR})
  add_compile_definitions(HAVE_CURL)
  # IF (${CURL_LIBRARY_RELEASE} MATCHES ".+static.*\\.lib$" OR ${CURL_LIBRARY_RELEASE} MATCHES ".+\\.a$")
  #   add_compile_definitions(CURL_STATIC)
  # ENDIF ()
ENDIF ()

