################################################################################
#
# liblzma
#

IF (HINT_DIR_INCLUDE)
  find_path(LIBLZMA_INCLUDE_DIRS NAMES "lzma.h" HINTS ${HINT_DIR_INCLUDE} PATH_SUFFIXES "lzma" NO_DEFAULT_PATH)
  find_library(LIBLZMA_LIBRARY_RELEASE NAMES "lzma" "liblzma" HINTS ${HINT_DIR_LIB} NO_DEFAULT_PATH)
  find_library(LIBLZMA_LIBRARY_DEBUG NAMES "lzmad" "liblzmad" HINTS ${HINT_DIR_LIBD} NO_DEFAULT_PATH)
  #MESSAGE(FATAL_ERROR " ${LIBLZMA_INCLUDE_DIRS} ${LIBLZMA_LIBRARIES} ")
ENDIF ()

IF (LIBLZMA_INCLUDE_DIRS AND LIBLZMA_LIBRARY_DEBUG)
  set(LIBLZMA_LIBRARIES ${LIBLZMA_LIBRARY_DEBUG})
  MESSAGE(STATUS "Found debug liblzma: ${LIBLZMA_LIBRARIES}")
ELSEIF (LIBLZMA_INCLUDE_DIRS AND LIBLZMA_LIBRARY_RELEASE)
  set(LIBLZMA_LIBRARIES ${LIBLZMA_LIBRARY_RELEASE})
  MESSAGE(STATUS "Found liblzma: ${LIBLZMA_LIBRARIES}")
ELSE()
  FIND_PACKAGE( LibLZMA )
ENDIF ()

IF (LIBLZMA_INCLUDE_DIRS AND LIBLZMA_LIBRARIES)
  INCLUDE_DIRECTORIES(${LIBLZMA_INCLUDE_DIRS})
  add_compile_definitions(HAVE_LIBLZMA)
  IF (${LIBLZMA_LIBRARY_RELEASE} MATCHES ".+static.*\\.lib$" OR ${LIBLZMA_LIBRARY_RELEASE} MATCHES ".+\\.a$")
    add_compile_definitions(LIBLZMA_STATIC)
  ENDIF ()
ENDIF ()
