################################################################################
#
# libxml2
#

IF (HINT_DIR_INCLUDE)
  UNSET(LIBXML2_LIBRARY)
  find_path(LIBXML2_INCLUDE_DIR NAMES "libxml/xpath.h" HINTS ${HINT_DIR_INCLUDE} PATH_SUFFIXES "libxml2" NO_CMAKE_FIND_ROOT_PATH)
  #SET(LIBXML2_INCLUDE_DIR ${LIBXML2_INCLUDE_DIR} CACHE PATH "" FORCE)
  #MESSAGE(FATAL_ERROR " ${LIBXML2_INCLUDE_DIR} ")
  find_library(LIBXML2_LIBRARY NAMES "xml2" "libxml2" HINTS ${HINT_DIR} PATH_SUFFIXES "lib" NO_CMAKE_FIND_ROOT_PATH)
  #SET(LIBXML2_LIBRARY ${LIBXML2_LIBRARY} CACHE FILEPATH "" FORCE)
  find_program(LIBXML2_XMLLINT_EXECUTABLE NAMES "xmllint" HINTS ${HINT_DIR} PATH_SUFFIXES "tools/libxml2" NO_CMAKE_FIND_ROOT_PATH)
ENDIF ()

IF (LIBXML2_INCLUDE_DIR AND LIBXML2_LIBRARY)
  MESSAGE(STATUS "Found libxml2: ${LIBXML2_LIBRARY}")
  INCLUDE_DIRECTORIES(${LIBXML2_INCLUDE_DIR})
  #add_compile_definitions(${LIBXML2_DEFINITIONS})
  IF ("${LIBXML2_LIBRARY}" MATCHES ".+static.*\\.lib" OR "${LIBXML2_TEST}" MATCHES ".+\\.a")
    add_compile_definitions(LIBXML_STATIC)
  ENDIF ()
ELSE()
  #find_path(LIBXML2_INCLUDE_DIR NAMES "libxml/tree.h" PATH_SUFFIXES "libxml2")
  #cmake_path(GET LIBXML2_INCLUDE_DIR PARENT_PATH _LIBXML2_INCLUDE_DIR)
  #SET(LIBXML2_INCLUDE_DIR ${LIBXML2_INCLUDE_DIR} CACHE PATH "" FORCE)
  #MESSAGE(FATAL_ERROR " 'libxml2' is a mandatory library")
  FIND_PACKAGE( LibXml2 )
ENDIF ()
