################################################################################
#
# libmicrohttpd
#

IF (HINT_DIR_INCLUDE)
  find_path(LIBMICROHTTPD_INCLUDE_DIR NAMES "microhttpd.h" HINTS ${HINT_DIR_INCLUDE})
  find_library(LIBMICROHTTPD_LIBRARY_DEBUG NAMES "libmicrohttpd.so" "libmicrohttpd" HINTS ${HINT_DIR_LIBD})
  find_library(LIBMICROHTTPD_LIBRARY_RELEASE NAMES "libmicrohttpd.so" "libmicrohttpd" HINTS ${HINT_DIR_LIB})
ENDIF ()

IF (LIBMICROHTTPD_INCLUDE_DIR AND LIBMICROHTTPD_LIBRARY_DEBUG)
  SET(LIBMICROHTTPD_LIBRARY ${LIBMICROHTTPD_LIBRARY_DEBUG})
  MESSAGE(STATUS "Found libmicrohttpd: ${LIBMICROHTTPD_LIBRARY}")
ELSEIF (LIBMICROHTTPD_INCLUDE_DIR AND LIBMICROHTTPD_LIBRARY_RELEASE)
  SET(LIBMICROHTTPD_LIBRARY ${LIBMICROHTTPD_LIBRARY_RELEASE})
  MESSAGE(STATUS "Found libmicrohttpd: ${LIBMICROHTTPD_LIBRARY}")
ELSE()
  #FIND_PACKAGE( LIBMICROHTTPD )
ENDIF ()
