################################################################################
#
# zlib
#

IF (HINT_DIR_INCLUDE)
  find_path(ZLIB_INCLUDE_DIR NAMES "zlib.h" HINTS ${HINT_DIR_INCLUDE} NO_DEFAULT_PATH)
  find_library(ZLIB_LIBRARY_DEBUG NAMES "zlib" "z" HINTS ${HINT_DIR_LIBD} NO_DEFAULT_PATH)
  find_library(ZLIB_LIBRARY_RELEASE NAMES "zlib" "z" HINTS ${HINT_DIR_LIB} NO_DEFAULT_PATH)
  #MESSAGE(FATAL_ERROR " ${ZLIB_INCLUDE_DIR} ${ZLIB_LIBRARY_RELEASE} ")
ENDIF ()

IF (ZLIB_INCLUDE_DIR AND ZLIB_LIBRARY_RELEASE)
  MESSAGE(STATUS "Found libz: ${ZLIB_LIBRARY_RELEASE}")
ELSE()
  FIND_PACKAGE( ZLIB )
ENDIF ()
