################################################################################
#
# libbase64
#

IF (HINT_DIR_INCLUDE)
  find_path(LIBBASE64_INCLUDE_DIR NAMES "libbase64.h" HINTS ${HINT_DIR_INCLUDE} NO_DEFAULT_PATH)
  find_library(LIBBASE64_LIBRARY_DEBUG NAMES "libbase64.a" "libbase64" HINTS ${HINT_DIR_LIBD} NO_DEFAULT_PATH)
  find_library(LIBBASE64_LIBRARY_RELEASE NAMES "libbase64.a" "libbase64" HINTS ${HINT_DIR_LIB} NO_DEFAULT_PATH)
ENDIF ()

IF (LIBBASE64_INCLUDE_DIR AND LIBBASE64_LIBRARY_DEBUG)
  SET(LIBBASE64_LIBRARY ${LIBBASE64_LIBRARY_DEBUG})
  MESSAGE(STATUS "Found libbase64: ${LIBBASE64_LIBRARY}")
ELSEIF (LIBBASE64_INCLUDE_DIR AND LIBBASE64_LIBRARY_RELEASE)
  SET(LIBBASE64_LIBRARY ${LIBBASE64_LIBRARY_RELEASE})
  MESSAGE(STATUS "Found libbase64: ${LIBBASE64_LIBRARY}")
ELSE()
  #FIND_PACKAGE( LIBBASE64 )
ENDIF ()
