// generated by 'svn info' and '', don't modify this content here !!

unsigned char git_info[] = {
	"Working Copy Root Path: /home/developer/cxproc-build/trunk\n"
	"Relative URL: ^/cxproc/trunk\n"
	"Last Changed Rev: 2582\n"
	"Last Changed Date: 2020-06-15 18:51:12 +0200 (Mo, 15 Jun 2020)\n"
	};

