// generated by 'svn info' and 'build/svn_revision.awk', don't modify this content here !!

#define CXP_VERSION_MAJOR    1

#define CXP_VERSION_MINOR    3

#define CXP_VERSION_STR      "v1.3"

#define CXP_VERSION_REVISION 2582

#define CXP_REVISION_STR     "r2582"

#define CXP_VERSION_BUILD    4432

#define CXP_VERSION_BUILD_STR "4432"

#define CXP_VERSION_URL      "http://arrakis.fritz.box:8187/cxproc/trunk"

