
FIND_PATH(CXPROC_SRC_DIR NAME "cxproc.c" HINTS "${PROJECT_SOURCE_DIR}/src")
#MESSAGE(STATUS "Using CXPROC_SRC_DIR: ${CXPROC_SRC_DIR}")

FIND_PATH(CXPROC_SRCLIB_DIR NAME "cgi-util" HINTS "${PROJECT_SOURCE_DIR}/third-party")

cmake_path(GET PROJECT_BINARY_DIR PARENT_PATH CXPROC_PREFIX)

SET(CXPROC_TEMP_DIR "${CXPROC_PREFIX}/tmp")
# working directory for tests
SET(CXPROC_TEST_DIR "${PROJECT_SOURCE_DIR}/test")

# helper: default path to use as HINT

cmake_path(GET PROJECT_SOURCE_DIR PARENT_PATH HINT_DIR_PARENT)
#MESSAGE(STATUS "Using HINT_DIR_PARENT: ${HINT_DIR_PARENT}")

cmake_path(GET PROJECT_BINARY_DIR PARENT_PATH HINT_DIR)
MESSAGE(STATUS "Using HINT_DIR: ${HINT_DIR}")

SET(HINT_DIR_INCLUDE "${HINT_DIR}/include")
SET(HINT_DIR_LIB "${HINT_DIR}/lib")
SET(HINT_DIR_LIBD "${HINT_DIR}/debug/lib")

